In [2]:
import pandas as pd
df = pd.read_csv("data/clean.csv")

In [5]:
df["sent_at"] = pd.to_datetime(df["sent_at"], errors = "coerce", utc = True, format= "mixed")

In [6]:
df["hour"] = df["sent_at"].dt.hour

In [7]:
df["is_weekend"] = df["sent_at"].dt.dayofweek >= 5

In [8]:
df.head()

,message_id,campaign_id,account_id,sender_name,recipient_id,network_provider,sent_at,delivered_at,delivery_status,error_code,message_parts,cost,hour,is_weekend
0,MSG00017303,CMP027,ACC0135,Sender_06,9XXXXX62,Unknown Provider,2026-05-18 11:23:42+00:00,2026-05-18 11:25:02,delivered,NaN,2.0,50.95,11,False
1,MSG00012498,CMP029,ACC0183,Sender_02,9XXXXX30,Provider_B,2026-05-08 07:10:19+00:00,2026-05-08 07:10:33,delivered,NaN,2.0,46.18,7,False
2,MSG00021899,CMP040,ACC0172,Sender_02,9XXXXX84,Provider_B,2026-04-21 00:17:03+00:00,2026-04-21 00:17:54,delivered,NaN,2.0,57.09,0,False
3,MSG00028690,CMP020,ACC0095,Sender_06,9XXXXX97,Provider_A,2026-05-06 08:42:41+00:00,2026-05-06 08:43:18,delivered,NaN,1.0,25.09,8,False
4,MSG00014531,CMP049,ACC0155,Sender_04,9XXXXX76,Provider_C,2026-04-21 07:52:00+00:00,2026-04-21 07:53:03,delivered,NaN,1.0,27.90,7,False

In [9]:
df = pd.get_dummies(df, columns = ["network_provider"])

In [10]:
df.head()

,message_id,campaign_id,account_id,sender_name,recipient_id,sent_at,delivered_at,delivery_status,error_code,message_parts,cost,hour,is_weekend,network_provider_Provider_A,network_provider_Provider_B,network_provider_Provider_C,network_provider_Provider_D,network_provider_Unknown Provider
0,MSG00017303,CMP027,ACC0135,Sender_06,9XXXXX62,2026-05-18 11:23:42+00:00,2026-05-18 11:25:02,delivered,NaN,2.0,50.95,11,False,False,False,False,False,True
1,MSG00012498,CMP029,ACC0183,Sender_02,9XXXXX30,2026-05-08 07:10:19+00:00,2026-05-08 07:10:33,delivered,NaN,2.0,46.18,7,False,False,True,False,False,False
2,MSG00021899,CMP040,ACC0172,Sender_02,9XXXXX84,2026-04-21 00:17:03+00:00,2026-04-21 00:17:54,delivered,NaN,2.0,57.09,0,False,False,True,False,False,False
3,MSG00028690,CMP020,ACC0095,Sender_06,9XXXXX97,2026-05-06 08:42:41+00:00,2026-05-06 08:43:18,delivered,NaN,1.0,25.09,8,False,True,False,False,False,False
4,MSG00014531,CMP049,ACC0155,Sender_04,9XXXXX76,2026-04-21 07:52:00+00:00,2026-04-21 07:53:03,delivered,NaN,1.0,27.90,7,False,False,False,True,False,False

In [14]:
df["parts_bucket"] = pd.cut(df["message_parts"], bins=[0, 1, 2, 3])
print(df["parts_bucket"].isna().sum())

285

In [15]:
df.head()

,message_id,campaign_id,account_id,sender_name,recipient_id,sent_at,delivered_at,delivery_status,error_code,message_parts,cost,hour,is_weekend,network_provider_Provider_A,network_provider_Provider_B,network_provider_Provider_C,network_provider_Provider_D,network_provider_Unknown Provider,parts_bucket
0,MSG00017303,CMP027,ACC0135,Sender_06,9XXXXX62,2026-05-18 11:23:42+00:00,2026-05-18 11:25:02,delivered,NaN,2.0,50.95,11,False,False,False,False,False,True,"(1, 2]"
1,MSG00012498,CMP029,ACC0183,Sender_02,9XXXXX30,2026-05-08 07:10:19+00:00,2026-05-08 07:10:33,delivered,NaN,2.0,46.18,7,False,False,True,False,False,False,"(1, 2]"
2,MSG00021899,CMP040,ACC0172,Sender_02,9XXXXX84,2026-04-21 00:17:03+00:00,2026-04-21 00:17:54,delivered,NaN,2.0,57.09,0,False,False,True,False,False,False,"(1, 2]"
3,MSG00028690,CMP020,ACC0095,Sender_06,9XXXXX97,2026-05-06 08:42:41+00:00,2026-05-06 08:43:18,delivered,NaN,1.0,25.09,8,False,True,False,False,False,False,"(0, 1]"
4,MSG00014531,CMP049,ACC0155,Sender_04,9XXXXX76,2026-04-21 07:52:00+00:00,2026-04-21 07:53:03,delivered,NaN,1.0,27.90,7,False,False,False,True,False,False,"(0, 1]"

In [16]:
df.groupby("delivery_status")["cost"].describe()

,count,mean,std,min,25%,50%,75%,max
delivery_status,,,,,,,,
delivered,27177.0,35.262560,53.232987,20.00,23.4600,26.980,43.2500,2711.00
expired,636.0,37.112752,17.991356,20.01,24.1900,27.990,48.5425,89.99
failed,1532.0,38.874047,63.102163,20.01,24.3175,27.995,49.7575,2407.50
rejected,343.0,37.156618,17.424928,20.10,24.4850,28.210,49.0700,89.40

In [20]:
df_featureTable = df.drop(columns = ["delivered_at", "error_code"])
df_featureTable.to_csv("day-4-featureTableData.csv", index = False)